version: '3'

services:
  fastapi-app:
    build: .
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "sqlite:latest"
    environment:
      - SQLITE_DATABASE=/data/mydatabase.db
    volumes:
      - ./data:/data